### ISSUE TITLE
Workflow / New/empty translations

### ISSUE THREAD

**Issue by ytsurk** [kyubisation/angular-t9n#38]
When I start a new project, and use the extracted file (with `ng extract-i18n`) as template for my locales (I added also the trgLang), t9n wont start until I deleted all <units> or added them empty <target> nodes.

> Failed to serialize target files
> [Nest] 34132  - 03.03.2023, 14:37:47   ERROR [ExceptionHandler] Cannot read properties of undefined (reading 'textContent')
> TypeError: Cannot read properties of undefined (reading 'textContent')
>     at Xlf2Deserializer._convertToString (C:\ws\zvs-vertragsmanager-web\node_modules\angular-t9n\server\index.js:945:19)
>     at Xlf2Deserializer._extractTarget (C:\ws\zvs-vertragsmanager-web\node_modules\angular-t9n\server\index.js:1124:21)
>     at Xlf2Deserializer._deserializeTargetUnit (C:\ws\zvs-vertragsmanager-web\node_modules\angular-t9n\server\index.js:1101:26)
>     at C:\ws\zvs-vertragsmanager-web\node_modules\angular-t9n\server\index.js:1084:30

You also can reproduce this, if you delete one <target> node in a messages.xx_YY.xlf file.

Further - as soon as I start t9n, all my translations will get empty <target> nodes, which seems quite bad to me.
As long as I do not provide translations, running my app the non source language will display empty texts ..
Is this the desired behavior? How can I mark translations as no availabe?

**Comment by fritteli** [comment]
We're also affected by this issue. Particularly, the empty `<target/>` tags with the resulting display of  no text at all tags hurt.

Are there any plans to do something about it?

**Comment by kyubisation** [comment]
Not at the time, as this project has quite low priority.
Feel free to contribute the necessary changes, if this is an urgent topic.

**Comment by cloakedch** [comment]
The changes in https://github.com/kyubisation/angular-t9n/pull/50 would solve our use case, but there might still be work left to do (XLFSerializer and XLFDeserializer, which I didn't touch). Also there are no tests in it.
